[package]
name = "day12"
version = "0.1.0"
edition = "2024"

[dependencies]
hashbrown = "0.16.1"
syn = { version = "2.0", features = ["full"] }
quote = "1.0"
good_lp = { version = "1.14.2", features = ["highs"], default-features = false }